name: nitflex

recipe: drupal8
config:
  webroot: ./web

proxy:
  node:
    - gatsby.lndo.site:8000

services:
  node:
    type: node:10.14
    port: 8000
    globals:
      gatsby-cli: "2.8.3"
      npm: "6.9.0"
    run:
      - echo "Installing Gatsby dependencies."
      - cd gatsby && npm install
  appserver:
    run:
      - /app/scripts/init.sh

events:
  post-start:
    - appserver: cd $LANDO_MOUNT && composer install

tooling:
  npm:
    service: node
  node:
    service: node
  gatsby:
    service: node
