name: nitflex

recipe: drupal8
config:
  webroot: drupal/web

services:
  appserver:
    build:
      - composer selfupdate --1
      - cd drupal && composer install
    run:
      - /app/drupal/scripts/init.sh
